### ISSUE TITLE
When i open the CEF remote debugging and open this theme it shows nothing

### ISSUE THREAD

**Issue by BadSpider1** [aleab/acav-we#3]
when i go to localhost:10000 it shows the theme and when i click it i just see a slightly gray background this appears in the console [photo](https://ctrlv.cz/shots/2021/12/25/8j7j.png)

**Comment by aleab** [comment]
The devtools' inspector doesn't work on Firefox unfortunately.

**Comment by BadSpider1** [comment]
Oh … i didnt expect that to be that simple … ill test it out later today
